# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zsq/hot-t-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zsq/hot-t-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zsq/hot-t-main/CMakeFiles /home/zsq/hot-t-main/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zsq/hot-t-main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named base

# Build rule for target.
base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 base
.PHONY : base

# fast build rule for target.
base/fast:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/build
.PHONY : base/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named coroutine_test

# Build rule for target.
coroutine_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coroutine_test
.PHONY : coroutine_test

# fast build rule for target.
coroutine_test/fast:
	$(MAKE) -f test/CMakeFiles/coroutine_test.dir/build.make test/CMakeFiles/coroutine_test.dir/build
.PHONY : coroutine_test/fast

#=============================================================================
# Target rules for targets named learning_simple_test

# Build rule for target.
learning_simple_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 learning_simple_test
.PHONY : learning_simple_test

# fast build rule for target.
learning_simple_test/fast:
	$(MAKE) -f test/CMakeFiles/learning_simple_test.dir/build.make test/CMakeFiles/learning_simple_test.dir/build
.PHONY : learning_simple_test/fast

#=============================================================================
# Target rules for targets named mem_pool_test

# Build rule for target.
mem_pool_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mem_pool_test
.PHONY : mem_pool_test

# fast build rule for target.
mem_pool_test/fast:
	$(MAKE) -f test/CMakeFiles/mem_pool_test.dir/build.make test/CMakeFiles/mem_pool_test.dir/build
.PHONY : mem_pool_test/fast

#=============================================================================
# Target rules for targets named micro_simple_test

# Build rule for target.
micro_simple_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 micro_simple_test
.PHONY : micro_simple_test

# fast build rule for target.
micro_simple_test/fast:
	$(MAKE) -f test/CMakeFiles/micro_simple_test.dir/build.make test/CMakeFiles/micro_simple_test.dir/build
.PHONY : micro_simple_test/fast

#=============================================================================
# Target rules for targets named mv_object_test

# Build rule for target.
mv_object_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mv_object_test
.PHONY : mv_object_test

# fast build rule for target.
mv_object_test/fast:
	$(MAKE) -f test/CMakeFiles/mv_object_test.dir/build.make test/CMakeFiles/mv_object_test.dir/build
.PHONY : mv_object_test/fast

#=============================================================================
# Target rules for targets named txn_simple_test

# Build rule for target.
txn_simple_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 txn_simple_test
.PHONY : txn_simple_test

# fast build rule for target.
txn_simple_test/fast:
	$(MAKE) -f test/CMakeFiles/txn_simple_test.dir/build.make test/CMakeFiles/txn_simple_test.dir/build
.PHONY : txn_simple_test/fast

#=============================================================================
# Target rules for targets named storage_test

# Build rule for target.
storage_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 storage_test
.PHONY : storage_test

# fast build rule for target.
storage_test/fast:
	$(MAKE) -f test/CMakeFiles/storage_test.dir/build.make test/CMakeFiles/storage_test.dir/build
.PHONY : storage_test/fast

#=============================================================================
# Target rules for targets named rrpc_test

# Build rule for target.
rrpc_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rrpc_test
.PHONY : rrpc_test

# fast build rule for target.
rrpc_test/fast:
	$(MAKE) -f test/CMakeFiles/rrpc_test.dir/build.make test/CMakeFiles/rrpc_test.dir/build
.PHONY : rrpc_test/fast

#=============================================================================
# Target rules for targets named rrpc_coroutine_test

# Build rule for target.
rrpc_coroutine_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rrpc_coroutine_test
.PHONY : rrpc_coroutine_test

# fast build rule for target.
rrpc_coroutine_test/fast:
	$(MAKE) -f test/CMakeFiles/rrpc_coroutine_test.dir/build.make test/CMakeFiles/rrpc_coroutine_test.dir/build
.PHONY : rrpc_coroutine_test/fast

#=============================================================================
# Target rules for targets named txn_skiplist_test

# Build rule for target.
txn_skiplist_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 txn_skiplist_test
.PHONY : txn_skiplist_test

# fast build rule for target.
txn_skiplist_test/fast:
	$(MAKE) -f test/CMakeFiles/txn_skiplist_test.dir/build.make test/CMakeFiles/txn_skiplist_test.dir/build
.PHONY : txn_skiplist_test/fast

#=============================================================================
# Target rules for targets named tpcc_bench_test

# Build rule for target.
tpcc_bench_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tpcc_bench_test
.PHONY : tpcc_bench_test

# fast build rule for target.
tpcc_bench_test/fast:
	$(MAKE) -f benchmark/CMakeFiles/tpcc_bench_test.dir/build.make benchmark/CMakeFiles/tpcc_bench_test.dir/build
.PHONY : tpcc_bench_test/fast

#=============================================================================
# Target rules for targets named bench_runner

# Build rule for target.
bench_runner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bench_runner
.PHONY : bench_runner

# fast build rule for target.
bench_runner/fast:
	$(MAKE) -f benchmark/CMakeFiles/bench_runner.dir/build.make benchmark/CMakeFiles/bench_runner.dir/build
.PHONY : bench_runner/fast

#=============================================================================
# Target rules for targets named skiplist_benchmark_test

# Build rule for target.
skiplist_benchmark_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 skiplist_benchmark_test
.PHONY : skiplist_benchmark_test

# fast build rule for target.
skiplist_benchmark_test/fast:
	$(MAKE) -f benchmark/CMakeFiles/skiplist_benchmark_test.dir/build.make benchmark/CMakeFiles/skiplist_benchmark_test.dir/build
.PHONY : skiplist_benchmark_test/fast

#=============================================================================
# Target rules for targets named micro_txn

# Build rule for target.
micro_txn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 micro_txn
.PHONY : micro_txn

# fast build rule for target.
micro_txn/fast:
	$(MAKE) -f benchmark/micro/CMakeFiles/micro_txn.dir/build.make benchmark/micro/CMakeFiles/micro_txn.dir/build
.PHONY : micro_txn/fast

#=============================================================================
# Target rules for targets named micro_db

# Build rule for target.
micro_db: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 micro_db
.PHONY : micro_db

# fast build rule for target.
micro_db/fast:
	$(MAKE) -f benchmark/micro/CMakeFiles/micro_db.dir/build.make benchmark/micro/CMakeFiles/micro_db.dir/build
.PHONY : micro_db/fast

#=============================================================================
# Target rules for targets named tpcc_txn

# Build rule for target.
tpcc_txn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tpcc_txn
.PHONY : tpcc_txn

# fast build rule for target.
tpcc_txn/fast:
	$(MAKE) -f benchmark/tpcc/CMakeFiles/tpcc_txn.dir/build.make benchmark/tpcc/CMakeFiles/tpcc_txn.dir/build
.PHONY : tpcc_txn/fast

#=============================================================================
# Target rules for targets named tpcc_db

# Build rule for target.
tpcc_db: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tpcc_db
.PHONY : tpcc_db

# fast build rule for target.
tpcc_db/fast:
	$(MAKE) -f benchmark/tpcc/CMakeFiles/tpcc_db.dir/build.make benchmark/tpcc/CMakeFiles/tpcc_db.dir/build
.PHONY : tpcc_db/fast

#=============================================================================
# Target rules for targets named smallbank_txn

# Build rule for target.
smallbank_txn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smallbank_txn
.PHONY : smallbank_txn

# fast build rule for target.
smallbank_txn/fast:
	$(MAKE) -f benchmark/smallbank/CMakeFiles/smallbank_txn.dir/build.make benchmark/smallbank/CMakeFiles/smallbank_txn.dir/build
.PHONY : smallbank_txn/fast

#=============================================================================
# Target rules for targets named smallbank_db

# Build rule for target.
smallbank_db: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smallbank_db
.PHONY : smallbank_db

# fast build rule for target.
smallbank_db/fast:
	$(MAKE) -f benchmark/smallbank/CMakeFiles/smallbank_db.dir/build.make benchmark/smallbank/CMakeFiles/smallbank_db.dir/build
.PHONY : smallbank_db/fast

src/coroutine_pool/coroutine.o: src/coroutine_pool/coroutine.cc.o

.PHONY : src/coroutine_pool/coroutine.o

# target to build an object file
src/coroutine_pool/coroutine.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/coroutine_pool/coroutine.cc.o
.PHONY : src/coroutine_pool/coroutine.cc.o

src/coroutine_pool/coroutine.i: src/coroutine_pool/coroutine.cc.i

.PHONY : src/coroutine_pool/coroutine.i

# target to preprocess a source file
src/coroutine_pool/coroutine.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/coroutine_pool/coroutine.cc.i
.PHONY : src/coroutine_pool/coroutine.cc.i

src/coroutine_pool/coroutine.s: src/coroutine_pool/coroutine.cc.s

.PHONY : src/coroutine_pool/coroutine.s

# target to generate assembly for a file
src/coroutine_pool/coroutine.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/coroutine_pool/coroutine.cc.s
.PHONY : src/coroutine_pool/coroutine.cc.s

src/coroutine_pool/coroutine_pool.o: src/coroutine_pool/coroutine_pool.cc.o

.PHONY : src/coroutine_pool/coroutine_pool.o

# target to build an object file
src/coroutine_pool/coroutine_pool.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/coroutine_pool/coroutine_pool.cc.o
.PHONY : src/coroutine_pool/coroutine_pool.cc.o

src/coroutine_pool/coroutine_pool.i: src/coroutine_pool/coroutine_pool.cc.i

.PHONY : src/coroutine_pool/coroutine_pool.i

# target to preprocess a source file
src/coroutine_pool/coroutine_pool.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/coroutine_pool/coroutine_pool.cc.i
.PHONY : src/coroutine_pool/coroutine_pool.cc.i

src/coroutine_pool/coroutine_pool.s: src/coroutine_pool/coroutine_pool.cc.s

.PHONY : src/coroutine_pool/coroutine_pool.s

# target to generate assembly for a file
src/coroutine_pool/coroutine_pool.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/coroutine_pool/coroutine_pool.cc.s
.PHONY : src/coroutine_pool/coroutine_pool.cc.s

src/coroutine_pool/scheduler.o: src/coroutine_pool/scheduler.cc.o

.PHONY : src/coroutine_pool/scheduler.o

# target to build an object file
src/coroutine_pool/scheduler.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/coroutine_pool/scheduler.cc.o
.PHONY : src/coroutine_pool/scheduler.cc.o

src/coroutine_pool/scheduler.i: src/coroutine_pool/scheduler.cc.i

.PHONY : src/coroutine_pool/scheduler.i

# target to preprocess a source file
src/coroutine_pool/scheduler.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/coroutine_pool/scheduler.cc.i
.PHONY : src/coroutine_pool/scheduler.cc.i

src/coroutine_pool/scheduler.s: src/coroutine_pool/scheduler.cc.s

.PHONY : src/coroutine_pool/scheduler.s

# target to generate assembly for a file
src/coroutine_pool/scheduler.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/coroutine_pool/scheduler.cc.s
.PHONY : src/coroutine_pool/scheduler.cc.s

src/dtxn/dtxn.o: src/dtxn/dtxn.cc.o

.PHONY : src/dtxn/dtxn.o

# target to build an object file
src/dtxn/dtxn.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/dtxn/dtxn.cc.o
.PHONY : src/dtxn/dtxn.cc.o

src/dtxn/dtxn.i: src/dtxn/dtxn.cc.i

.PHONY : src/dtxn/dtxn.i

# target to preprocess a source file
src/dtxn/dtxn.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/dtxn/dtxn.cc.i
.PHONY : src/dtxn/dtxn.cc.i

src/dtxn/dtxn.s: src/dtxn/dtxn.cc.s

.PHONY : src/dtxn/dtxn.s

# target to generate assembly for a file
src/dtxn/dtxn.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/dtxn/dtxn.cc.s
.PHONY : src/dtxn/dtxn.cc.s

src/dtxn/impl/occ.o: src/dtxn/impl/occ.cc.o

.PHONY : src/dtxn/impl/occ.o

# target to build an object file
src/dtxn/impl/occ.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/dtxn/impl/occ.cc.o
.PHONY : src/dtxn/impl/occ.cc.o

src/dtxn/impl/occ.i: src/dtxn/impl/occ.cc.i

.PHONY : src/dtxn/impl/occ.i

# target to preprocess a source file
src/dtxn/impl/occ.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/dtxn/impl/occ.cc.i
.PHONY : src/dtxn/impl/occ.cc.i

src/dtxn/impl/occ.s: src/dtxn/impl/occ.cc.s

.PHONY : src/dtxn/impl/occ.s

# target to generate assembly for a file
src/dtxn/impl/occ.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/dtxn/impl/occ.cc.s
.PHONY : src/dtxn/impl/occ.cc.s

src/dtxn/impl/toc.o: src/dtxn/impl/toc.cc.o

.PHONY : src/dtxn/impl/toc.o

# target to build an object file
src/dtxn/impl/toc.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/dtxn/impl/toc.cc.o
.PHONY : src/dtxn/impl/toc.cc.o

src/dtxn/impl/toc.i: src/dtxn/impl/toc.cc.i

.PHONY : src/dtxn/impl/toc.i

# target to preprocess a source file
src/dtxn/impl/toc.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/dtxn/impl/toc.cc.i
.PHONY : src/dtxn/impl/toc.cc.i

src/dtxn/impl/toc.s: src/dtxn/impl/toc.cc.s

.PHONY : src/dtxn/impl/toc.s

# target to generate assembly for a file
src/dtxn/impl/toc.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/dtxn/impl/toc.cc.s
.PHONY : src/dtxn/impl/toc.cc.s

src/dtxn/takeout_lock.o: src/dtxn/takeout_lock.cc.o

.PHONY : src/dtxn/takeout_lock.o

# target to build an object file
src/dtxn/takeout_lock.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/dtxn/takeout_lock.cc.o
.PHONY : src/dtxn/takeout_lock.cc.o

src/dtxn/takeout_lock.i: src/dtxn/takeout_lock.cc.i

.PHONY : src/dtxn/takeout_lock.i

# target to preprocess a source file
src/dtxn/takeout_lock.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/dtxn/takeout_lock.cc.i
.PHONY : src/dtxn/takeout_lock.cc.i

src/dtxn/takeout_lock.s: src/dtxn/takeout_lock.cc.s

.PHONY : src/dtxn/takeout_lock.s

# target to generate assembly for a file
src/dtxn/takeout_lock.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/dtxn/takeout_lock.cc.s
.PHONY : src/dtxn/takeout_lock.cc.s

src/proto/rdma.o: src/proto/rdma.cc.o

.PHONY : src/proto/rdma.o

# target to build an object file
src/proto/rdma.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/proto/rdma.cc.o
.PHONY : src/proto/rdma.cc.o

src/proto/rdma.i: src/proto/rdma.cc.i

.PHONY : src/proto/rdma.i

# target to preprocess a source file
src/proto/rdma.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/proto/rdma.cc.i
.PHONY : src/proto/rdma.cc.i

src/proto/rdma.s: src/proto/rdma.cc.s

.PHONY : src/proto/rdma.s

# target to generate assembly for a file
src/proto/rdma.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/proto/rdma.cc.s
.PHONY : src/proto/rdma.cc.s

src/proto/rpc.o: src/proto/rpc.cc.o

.PHONY : src/proto/rpc.o

# target to build an object file
src/proto/rpc.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/proto/rpc.cc.o
.PHONY : src/proto/rpc.cc.o

src/proto/rpc.i: src/proto/rpc.cc.i

.PHONY : src/proto/rpc.i

# target to preprocess a source file
src/proto/rpc.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/proto/rpc.cc.i
.PHONY : src/proto/rpc.cc.i

src/proto/rpc.s: src/proto/rpc.cc.s

.PHONY : src/proto/rpc.s

# target to generate assembly for a file
src/proto/rpc.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/proto/rpc.cc.s
.PHONY : src/proto/rpc.cc.s

src/rrpc/rdma_cm.o: src/rrpc/rdma_cm.cc.o

.PHONY : src/rrpc/rdma_cm.o

# target to build an object file
src/rrpc/rdma_cm.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/rdma_cm.cc.o
.PHONY : src/rrpc/rdma_cm.cc.o

src/rrpc/rdma_cm.i: src/rrpc/rdma_cm.cc.i

.PHONY : src/rrpc/rdma_cm.i

# target to preprocess a source file
src/rrpc/rdma_cm.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/rdma_cm.cc.i
.PHONY : src/rrpc/rdma_cm.cc.i

src/rrpc/rdma_cm.s: src/rrpc/rdma_cm.cc.s

.PHONY : src/rrpc/rdma_cm.s

# target to generate assembly for a file
src/rrpc/rdma_cm.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/rdma_cm.cc.s
.PHONY : src/rrpc/rdma_cm.cc.s

src/rrpc/rdma_poll_worker.o: src/rrpc/rdma_poll_worker.cc.o

.PHONY : src/rrpc/rdma_poll_worker.o

# target to build an object file
src/rrpc/rdma_poll_worker.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/rdma_poll_worker.cc.o
.PHONY : src/rrpc/rdma_poll_worker.cc.o

src/rrpc/rdma_poll_worker.i: src/rrpc/rdma_poll_worker.cc.i

.PHONY : src/rrpc/rdma_poll_worker.i

# target to preprocess a source file
src/rrpc/rdma_poll_worker.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/rdma_poll_worker.cc.i
.PHONY : src/rrpc/rdma_poll_worker.cc.i

src/rrpc/rdma_poll_worker.s: src/rrpc/rdma_poll_worker.cc.s

.PHONY : src/rrpc/rdma_poll_worker.s

# target to generate assembly for a file
src/rrpc/rdma_poll_worker.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/rdma_poll_worker.cc.s
.PHONY : src/rrpc/rdma_poll_worker.cc.s

src/rrpc/rdma_straw.o: src/rrpc/rdma_straw.cc.o

.PHONY : src/rrpc/rdma_straw.o

# target to build an object file
src/rrpc/rdma_straw.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/rdma_straw.cc.o
.PHONY : src/rrpc/rdma_straw.cc.o

src/rrpc/rdma_straw.i: src/rrpc/rdma_straw.cc.i

.PHONY : src/rrpc/rdma_straw.i

# target to preprocess a source file
src/rrpc/rdma_straw.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/rdma_straw.cc.i
.PHONY : src/rrpc/rdma_straw.cc.i

src/rrpc/rdma_straw.s: src/rrpc/rdma_straw.cc.s

.PHONY : src/rrpc/rdma_straw.s

# target to generate assembly for a file
src/rrpc/rdma_straw.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/rdma_straw.cc.s
.PHONY : src/rrpc/rdma_straw.cc.s

src/rrpc/ring_buf.o: src/rrpc/ring_buf.cc.o

.PHONY : src/rrpc/ring_buf.o

# target to build an object file
src/rrpc/ring_buf.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/ring_buf.cc.o
.PHONY : src/rrpc/ring_buf.cc.o

src/rrpc/ring_buf.i: src/rrpc/ring_buf.cc.i

.PHONY : src/rrpc/ring_buf.i

# target to preprocess a source file
src/rrpc/ring_buf.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/ring_buf.cc.i
.PHONY : src/rrpc/ring_buf.cc.i

src/rrpc/ring_buf.s: src/rrpc/ring_buf.cc.s

.PHONY : src/rrpc/ring_buf.s

# target to generate assembly for a file
src/rrpc/ring_buf.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/ring_buf.cc.s
.PHONY : src/rrpc/ring_buf.cc.s

src/rrpc/rocket.o: src/rrpc/rocket.cc.o

.PHONY : src/rrpc/rocket.o

# target to build an object file
src/rrpc/rocket.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/rocket.cc.o
.PHONY : src/rrpc/rocket.cc.o

src/rrpc/rocket.i: src/rrpc/rocket.cc.i

.PHONY : src/rrpc/rocket.i

# target to preprocess a source file
src/rrpc/rocket.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/rocket.cc.i
.PHONY : src/rrpc/rocket.cc.i

src/rrpc/rocket.s: src/rrpc/rocket.cc.s

.PHONY : src/rrpc/rocket.s

# target to generate assembly for a file
src/rrpc/rocket.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/rocket.cc.s
.PHONY : src/rrpc/rocket.cc.s

src/rrpc/rrpc_callbacks.o: src/rrpc/rrpc_callbacks.cc.o

.PHONY : src/rrpc/rrpc_callbacks.o

# target to build an object file
src/rrpc/rrpc_callbacks.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/rrpc_callbacks.cc.o
.PHONY : src/rrpc/rrpc_callbacks.cc.o

src/rrpc/rrpc_callbacks.i: src/rrpc/rrpc_callbacks.cc.i

.PHONY : src/rrpc/rrpc_callbacks.i

# target to preprocess a source file
src/rrpc/rrpc_callbacks.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/rrpc_callbacks.cc.i
.PHONY : src/rrpc/rrpc_callbacks.cc.i

src/rrpc/rrpc_callbacks.s: src/rrpc/rrpc_callbacks.cc.s

.PHONY : src/rrpc/rrpc_callbacks.s

# target to generate assembly for a file
src/rrpc/rrpc_callbacks.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/rrpc_callbacks.cc.s
.PHONY : src/rrpc/rrpc_callbacks.cc.s

src/rrpc/tcp_adaptor.o: src/rrpc/tcp_adaptor.cc.o

.PHONY : src/rrpc/tcp_adaptor.o

# target to build an object file
src/rrpc/tcp_adaptor.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/tcp_adaptor.cc.o
.PHONY : src/rrpc/tcp_adaptor.cc.o

src/rrpc/tcp_adaptor.i: src/rrpc/tcp_adaptor.cc.i

.PHONY : src/rrpc/tcp_adaptor.i

# target to preprocess a source file
src/rrpc/tcp_adaptor.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/tcp_adaptor.cc.i
.PHONY : src/rrpc/tcp_adaptor.cc.i

src/rrpc/tcp_adaptor.s: src/rrpc/tcp_adaptor.cc.s

.PHONY : src/rrpc/tcp_adaptor.s

# target to generate assembly for a file
src/rrpc/tcp_adaptor.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/tcp_adaptor.cc.s
.PHONY : src/rrpc/tcp_adaptor.cc.s

src/rrpc/tcp_callbacks.o: src/rrpc/tcp_callbacks.cc.o

.PHONY : src/rrpc/tcp_callbacks.o

# target to build an object file
src/rrpc/tcp_callbacks.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/tcp_callbacks.cc.o
.PHONY : src/rrpc/tcp_callbacks.cc.o

src/rrpc/tcp_callbacks.i: src/rrpc/tcp_callbacks.cc.i

.PHONY : src/rrpc/tcp_callbacks.i

# target to preprocess a source file
src/rrpc/tcp_callbacks.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/tcp_callbacks.cc.i
.PHONY : src/rrpc/tcp_callbacks.cc.i

src/rrpc/tcp_callbacks.s: src/rrpc/tcp_callbacks.cc.s

.PHONY : src/rrpc/tcp_callbacks.s

# target to generate assembly for a file
src/rrpc/tcp_callbacks.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/rrpc/tcp_callbacks.cc.s
.PHONY : src/rrpc/tcp_callbacks.cc.s

src/storage/db.o: src/storage/db.cc.o

.PHONY : src/storage/db.o

# target to build an object file
src/storage/db.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/storage/db.cc.o
.PHONY : src/storage/db.cc.o

src/storage/db.i: src/storage/db.cc.i

.PHONY : src/storage/db.i

# target to preprocess a source file
src/storage/db.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/storage/db.cc.i
.PHONY : src/storage/db.cc.i

src/storage/db.s: src/storage/db.cc.s

.PHONY : src/storage/db.s

# target to generate assembly for a file
src/storage/db.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/storage/db.cc.s
.PHONY : src/storage/db.cc.s

src/storage/object.o: src/storage/object.cc.o

.PHONY : src/storage/object.o

# target to build an object file
src/storage/object.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/storage/object.cc.o
.PHONY : src/storage/object.cc.o

src/storage/object.i: src/storage/object.cc.i

.PHONY : src/storage/object.i

# target to preprocess a source file
src/storage/object.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/storage/object.cc.i
.PHONY : src/storage/object.cc.i

src/storage/object.s: src/storage/object.cc.s

.PHONY : src/storage/object.s

# target to generate assembly for a file
src/storage/object.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/storage/object.cc.s
.PHONY : src/storage/object.cc.s

src/storage/simple_db.o: src/storage/simple_db.cc.o

.PHONY : src/storage/simple_db.o

# target to build an object file
src/storage/simple_db.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/storage/simple_db.cc.o
.PHONY : src/storage/simple_db.cc.o

src/storage/simple_db.i: src/storage/simple_db.cc.i

.PHONY : src/storage/simple_db.i

# target to preprocess a source file
src/storage/simple_db.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/storage/simple_db.cc.i
.PHONY : src/storage/simple_db.cc.i

src/storage/simple_db.s: src/storage/simple_db.cc.s

.PHONY : src/storage/simple_db.s

# target to generate assembly for a file
src/storage/simple_db.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/storage/simple_db.cc.s
.PHONY : src/storage/simple_db.cc.s

src/util/mem_pool.o: src/util/mem_pool.cc.o

.PHONY : src/util/mem_pool.o

# target to build an object file
src/util/mem_pool.cc.o:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/util/mem_pool.cc.o
.PHONY : src/util/mem_pool.cc.o

src/util/mem_pool.i: src/util/mem_pool.cc.i

.PHONY : src/util/mem_pool.i

# target to preprocess a source file
src/util/mem_pool.cc.i:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/util/mem_pool.cc.i
.PHONY : src/util/mem_pool.cc.i

src/util/mem_pool.s: src/util/mem_pool.cc.s

.PHONY : src/util/mem_pool.s

# target to generate assembly for a file
src/util/mem_pool.cc.s:
	$(MAKE) -f CMakeFiles/base.dir/build.make CMakeFiles/base.dir/src/util/mem_pool.cc.s
.PHONY : src/util/mem_pool.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... base"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... coroutine_test"
	@echo "... learning_simple_test"
	@echo "... mem_pool_test"
	@echo "... micro_simple_test"
	@echo "... mv_object_test"
	@echo "... txn_simple_test"
	@echo "... storage_test"
	@echo "... rrpc_test"
	@echo "... rrpc_coroutine_test"
	@echo "... txn_skiplist_test"
	@echo "... tpcc_bench_test"
	@echo "... bench_runner"
	@echo "... skiplist_benchmark_test"
	@echo "... micro_txn"
	@echo "... micro_db"
	@echo "... tpcc_txn"
	@echo "... tpcc_db"
	@echo "... smallbank_txn"
	@echo "... smallbank_db"
	@echo "... src/coroutine_pool/coroutine.o"
	@echo "... src/coroutine_pool/coroutine.i"
	@echo "... src/coroutine_pool/coroutine.s"
	@echo "... src/coroutine_pool/coroutine_pool.o"
	@echo "... src/coroutine_pool/coroutine_pool.i"
	@echo "... src/coroutine_pool/coroutine_pool.s"
	@echo "... src/coroutine_pool/scheduler.o"
	@echo "... src/coroutine_pool/scheduler.i"
	@echo "... src/coroutine_pool/scheduler.s"
	@echo "... src/dtxn/dtxn.o"
	@echo "... src/dtxn/dtxn.i"
	@echo "... src/dtxn/dtxn.s"
	@echo "... src/dtxn/impl/occ.o"
	@echo "... src/dtxn/impl/occ.i"
	@echo "... src/dtxn/impl/occ.s"
	@echo "... src/dtxn/impl/toc.o"
	@echo "... src/dtxn/impl/toc.i"
	@echo "... src/dtxn/impl/toc.s"
	@echo "... src/dtxn/takeout_lock.o"
	@echo "... src/dtxn/takeout_lock.i"
	@echo "... src/dtxn/takeout_lock.s"
	@echo "... src/proto/rdma.o"
	@echo "... src/proto/rdma.i"
	@echo "... src/proto/rdma.s"
	@echo "... src/proto/rpc.o"
	@echo "... src/proto/rpc.i"
	@echo "... src/proto/rpc.s"
	@echo "... src/rrpc/rdma_cm.o"
	@echo "... src/rrpc/rdma_cm.i"
	@echo "... src/rrpc/rdma_cm.s"
	@echo "... src/rrpc/rdma_poll_worker.o"
	@echo "... src/rrpc/rdma_poll_worker.i"
	@echo "... src/rrpc/rdma_poll_worker.s"
	@echo "... src/rrpc/rdma_straw.o"
	@echo "... src/rrpc/rdma_straw.i"
	@echo "... src/rrpc/rdma_straw.s"
	@echo "... src/rrpc/ring_buf.o"
	@echo "... src/rrpc/ring_buf.i"
	@echo "... src/rrpc/ring_buf.s"
	@echo "... src/rrpc/rocket.o"
	@echo "... src/rrpc/rocket.i"
	@echo "... src/rrpc/rocket.s"
	@echo "... src/rrpc/rrpc_callbacks.o"
	@echo "... src/rrpc/rrpc_callbacks.i"
	@echo "... src/rrpc/rrpc_callbacks.s"
	@echo "... src/rrpc/tcp_adaptor.o"
	@echo "... src/rrpc/tcp_adaptor.i"
	@echo "... src/rrpc/tcp_adaptor.s"
	@echo "... src/rrpc/tcp_callbacks.o"
	@echo "... src/rrpc/tcp_callbacks.i"
	@echo "... src/rrpc/tcp_callbacks.s"
	@echo "... src/storage/db.o"
	@echo "... src/storage/db.i"
	@echo "... src/storage/db.s"
	@echo "... src/storage/object.o"
	@echo "... src/storage/object.i"
	@echo "... src/storage/object.s"
	@echo "... src/storage/simple_db.o"
	@echo "... src/storage/simple_db.i"
	@echo "... src/storage/simple_db.s"
	@echo "... src/util/mem_pool.o"
	@echo "... src/util/mem_pool.i"
	@echo "... src/util/mem_pool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

